-- ====================================================================
-- PLANTAS MEDICINALES COMPLETAS - INFORMACIÓN REAL Y VERIFICADA
-- ====================================================================
-- Este script inserta plantas con TODOS los campos completos
-- Información basada en estudios científicos y literatura médica
-- ====================================================================

-- IMPORTANTE: Primero limpia la tabla (opcional, descomenta si quieres)
-- TRUNCATE TABLE plants CASCADE;

-- ====================================================================
-- 1. MANZANILLA (Matricaria chamomilla)
-- ====================================================================
INSERT INTO plants (
  name,
  scientific_name,
  description,
  category,
  properties,
  tags,
  ailments,
  usage_instructions,
  warnings,
  therapeutic_indications,
  contraindications,
  side_effects,
  drug_interactions,
  dosage_adults,
  dosage_children,
  administration_route,
  preparation_method,
  safe_pregnancy,
  safe_lactation,
  safe_children,
  evidence_level,
  clinical_studies,
  nursing_notes,
  monitoring_parameters,
  scientific_article_url
) VALUES (
  'Manzanilla',
  'Matricaria chamomilla',
  'Planta medicinal ampliamente utilizada por sus propiedades antiinflamatorias, antiespasmódicas y sedantes suaves. Sus flores contienen aceites esenciales con apigenina, un flavonoide con efectos calmantes.',
  'Digestivas',
  'Antiinflamatoria, antiespasmódica, sedante suave, carminativa, cicatrizante',
  ARRAY['digestión', 'relajante', 'segura', 'niños', 'insomnio'],
  ARRAY['insomnio', 'ansiedad', 'gastritis', 'cólicos', 'inflamación'],
  'Preparar infusión con 1-2 cucharaditas (2-3g) de flores secas en 150ml de agua caliente. Dejar reposar 5-10 minutos tapado. Consumir 3-4 veces al día entre comidas. Para uso tópico, aplicar la infusión fría en compresas.',
  'Evitar en personas con alergia a la familia Asteraceae (margaritas, girasoles). No usar aceite esencial puro en niños menores de 3 años. Suspender 2 semanas antes de cirugías.',
  'Tratamiento de trastornos gastrointestinales (dispepsia, gastritis, cólicos). Manejo de ansiedad leve y trastornos del sueño. Inflamación de mucosas (oral, ocular, genital). Heridas superficiales y dermatitis.',
  'Hipersensibilidad conocida a plantas de la familia Asteraceae. Alergia al polen. Uso concomitante con anticoagulantes (warfarina) sin supervisión médica.',
  'Reacciones alérgicas (dermatitis de contacto, conjuntivitis). Raramente: vómitos por dosis excesivas. Somnolencia en dosis altas.',
  'Puede potenciar efectos de sedantes, ansiolíticos y alcohol. Interacción teórica con anticoagulantes (warfarina) y antiagregantes plaquetarios. Puede aumentar riesgo de sangrado con AINEs.',
  'Infusión: 150ml 3-4 veces al día. Tintura (1:5): 15-30 gotas 3 veces al día. Extracto fluido: 1-4ml 3 veces al día.',
  'Mayores de 6 meses: 30-60ml de infusión diluida 2-3 veces al día. Mayores de 5 años: 100ml de infusión 2-3 veces al día. No usar aceite esencial en menores de 3 años.',
  ARRAY['oral', 'topica'],
  'Infusión: 2-3g de flores secas en 150ml de agua a 90°C, reposar 5-10 minutos tapado. Tintura: macerar 100g de flores en 500ml de alcohol 40° durante 15 días, filtrar. Compresas: empapar gasa en infusión fría.',
  true,
  true,
  true,
  'Alto',
  'Srivastava JK, Shankar E, Gupta S. Chamomile: A herbal medicine of the past with bright future. Mol Med Rep. 2010;3(6):895-901. | McKay DL, Blumberg JB. A review of the bioactivity and potential health benefits of chamomile tea. Phytother Res. 2006;20(7):519-530.',
  'Monitorear respuesta terapéutica en pacientes con trastornos digestivos. Observar signos de alergia en primera administración. Educar sobre preparación correcta de infusión (tapada para conservar aceites volátiles).',
  ARRAY['signos de alergia', 'calidad del sueño', 'síntomas gastrointestinales'],
  'https://pubmed.ncbi.nlm.nih.gov/22228617/'
);

-- ====================================================================
-- 2. JENGIBRE (Zingiber officinale)
-- ====================================================================
INSERT INTO plants (
  name,
  scientific_name,
  description,
  category,
  properties,
  tags,
  ailments,
  usage_instructions,
  warnings,
  therapeutic_indications,
  contraindications,
  side_effects,
  drug_interactions,
  dosage_adults,
  dosage_children,
  administration_route,
  preparation_method,
  safe_pregnancy,
  safe_lactation,
  safe_children,
  evidence_level,
  clinical_studies,
  nursing_notes,
  monitoring_parameters,
  scientific_article_url
) VALUES (
  'Jengibre',
  'Zingiber officinale',
  'Raíz aromática con potentes propiedades antiinflamatorias y antieméticas. Contiene gingeroles y shogaoles que inhiben la producción de prostaglandinas y modulan receptores de serotonina.',
  'Digestivas',
  'Antiemético, antiinflamatorio, antioxidante, digestivo, termogénico',
  ARRAY['náuseas', 'digestión', 'antiinflamatorio', 'circulación'],
  ARRAY['náuseas', 'vómitos', 'mareos', 'dolor muscular', 'artritis'],
  'Para náuseas: consumir 1g de jengibre fresco o 250mg de polvo 4 veces al día. Masticar pequeños trozos de jengibre fresco o tomar infusión. Puede consumirse antes de viajes. Para inflamación: 2-4g diarios divididos en varias tomas.',
  'Evitar dosis altas (>4g/día) durante el embarazo. No consumir antes de cirugías (suspender 1 semana antes). Precaución en pacientes con cálculos biliares. Puede causar ardor estomacal en dosis altas.',
  'Prevención y tratamiento de náuseas (gestacional, postoperatoria, por quimioterapia, mareo por movimiento). Osteoartritis y dolor musculoesquelético. Dispepsia funcional.',
  'Alergia conocida al jengibre. Cálculos biliares activos. Trastornos de coagulación severos. Evitar dosis altas en embarazo (especialmente primer trimestre).',
  'Acidez estomacal, eructos, molestias gastrointestinales leves. Raramente: diarrea, irritación bucal. Puede aumentar sangrado en dosis muy altas.',
  'Puede potenciar efectos de anticoagulantes (warfarina) y antiagregantes plaquetarios. Posible interacción con antidiabéticos (puede reducir glucosa). Puede aumentar absorción de algunos medicamentos.',
  'Polvo: 250mg-1g 4 veces al día (máximo 4g/día). Jengibre fresco: 2-4g diarios. Tintura (1:5): 1.5-3ml 3 veces al día. Para náuseas gestacionales: máximo 1g/día dividido en 4 tomas.',
  'Mayores de 2 años: 1⁄4 de dosis de adulto. Mayores de 6 años: 1⁄2 dosis de adulto. No recomendado en menores de 2 años. Para náuseas: pequeñas cantidades (250mg) según necesidad.',
  ARRAY['oral'],
  'Infusión: rallar 2-3g de rizoma fresco, agregar 250ml de agua hirviendo, reposar 10 minutos. Té: hervir rodajas finas 10-15 minutos. Polvo: añadir 1⁄2 cucharadita a alimentos o bebidas. Puede endulzar con miel.',
  true,
  true,
  true,
  'Alto',
  'Bode AM, Dong Z. The Amazing and Mighty Ginger. In: Benzie IFF, Wachtel-Galor S, editors. Herbal Medicine: Biomolecular and Clinical Aspects. 2nd edition. 2011. | Viljoen E, et al. A systematic review and meta-analysis of the effect and safety of ginger in the treatment of pregnancy-associated nausea and vomiting. Nutr J. 2014;13:20.',
  'Monitorear glucemia en pacientes diabéticos. Evaluar respuesta a náuseas dentro de 30-60 minutos. Preguntar sobre uso de anticoagulantes. Advertir sobre suspensión pre-quirúrgica.',
  ARRAY['glucemia', 'tiempo de coagulación', 'respuesta antiemética', 'síntomas gastrointestinales'],
  'https://pubmed.ncbi.nlm.nih.gov/24642205/'
);

-- ====================================================================
-- 3. LAVANDA (Lavandula angustifolia)
-- ====================================================================
INSERT INTO plants (
  name,
  scientific_name,
  description,
  category,
  properties,
  tags,
  ailments,
  usage_instructions,
  warnings,
  therapeutic_indications,
  contraindications,
  side_effects,
  drug_interactions,
  dosage_adults,
  dosage_children,
  administration_route,
  preparation_method,
  safe_pregnancy,
  safe_lactation,
  safe_children,
  evidence_level,
  clinical_studies,
  nursing_notes,
  monitoring_parameters,
  scientific_article_url
) VALUES (
  'Lavanda',
  'Lavandula angustifolia',
  'Planta aromática con propiedades ansiolíticas y sedantes. Su aceite esencial contiene linalool y acetato de linalilo, compuestos que modulan neurotransmisores GABA y reducen actividad del sistema nervioso simpático.',
  'Relajantes',
  'Ansiolítico, sedante suave, antiespasmódico, antiséptico, cicatrizante',
  ARRAY['ansiedad', 'insomnio', 'relajante', 'aromático', 'seguro'],
  ARRAY['ansiedad', 'insomnio', 'estrés', 'dolor de cabeza', 'tensión'],
  'Aromaterapia: difundir 3-5 gotas de aceite esencial puro durante 15-30 minutos antes de dormir. Oral: infusión con 1-2 cucharaditas de flores secas 2-3 veces al día. Tópico: aceite diluido al 2-5% en aceite portador para masajes relajantes.',
  'No ingerir aceite esencial puro (puede ser tóxico). Evitar uso oral prolongado. Puede causar somnolencia, no conducir después de uso. El aceite esencial puede causar dermatitis de contacto en pieles sensibles. Diluir siempre antes de aplicación tópica.',
  'Trastorno de ansiedad generalizada leve a moderado. Insomnio de conciliación. Agitación nerviosa. Cefalea tensional. Heridas superficiales y quemaduras leves (uso tópico).',
  'Alergia conocida a lavanda o familia Lamiaceae. No usar aceite esencial puro en embarazo (especialmente primer trimestre). Evitar en epilepsia sin supervisión. Niños menores de 3 años: solo aromaterapia supervisada.',
  'Somnolencia, cefalea (raramente). Náuseas y estreñimiento con uso oral. Dermatitis de contacto con aceite esencial sin diluir. Reacciones alérgicas (rash, prurito).',
  'Potencia efectos de sedantes, benzodiacepinas y alcohol. Puede aumentar somnolencia con antihistamínicos. Posible interacción con medicamentos metabolizados por CYP450.',
  'Infusión: 150-200ml 2-3 veces al día. Aceite esencial por vía oral: 1-2 gotas en miel o azúcar (uso ocasional, bajo supervisión). Aromaterapia: 3-5 gotas en difusor. Baño relajante: 5-10 gotas en agua tibia.',
  'Mayores de 3 años: aromaterapia supervisada (1-2 gotas en difusor, sesiones cortas de 5-10 minutos). Mayores de 6 años: infusión suave (50-100ml). No usar aceite esencial sin diluir. Evitar ingesta de aceite en niños.',
  ARRAY['oral', 'topica', 'inhalacion'],
  'Infusión: 1-2 cucharaditas de flores en 200ml de agua a 85°C, reposar 10 minutos tapado. Aceite de masaje: diluir 10-15 gotas de aceite esencial en 30ml de aceite de almendras. Saquitos aromáticos: flores secas en tela para almohada.',
  false,
  true,
  true,
  'Moderado',
  'Koulivand PH, Khaleghi Ghadiri M, Gorji A. Lavender and the nervous system. Evid Based Complement Alternat Med. 2013;2013:681304. | Kasper S, et al. Lavender oil preparation Silexan is effective in generalized anxiety disorder. Int Clin Psychopharmacol. 2014;29(1):21-27.',
  'Monitorear calidad del sueño y niveles de ansiedad. Advertir sobre no conducir después de uso. Enseñar dilución correcta de aceite esencial (nunca puro en piel). Evaluar alergias previas a Lamiaceae.',
  ARRAY['calidad del sueño', 'escala de ansiedad', 'signos de alergia', 'somnolencia diurna'],
  'https://pubmed.ncbi.nlm.nih.gov/24063515/'
);

-- ====================================================================
-- 4. VALERIANA (Valeriana officinalis)
-- ====================================================================
INSERT INTO plants (
  name,
  scientific_name,
  description,
  category,
  properties,
  tags,
  ailments,
  usage_instructions,
  warnings,
  therapeutic_indications,
  contraindications,
  side_effects,
  drug_interactions,
  dosage_adults,
  dosage_children,
  administration_route,
  preparation_method,
  safe_pregnancy,
  safe_lactation,
  safe_children,
  evidence_level,
  clinical_studies,
  nursing_notes,
  monitoring_parameters,
  scientific_article_url
) VALUES (
  'Valeriana',
  'Valeriana officinalis',
  'Raíz con potentes propiedades sedantes e hipnóticas. Contiene ácido valerénico que aumenta niveles de GABA en el cerebro, induciendo relajación y sueño. Considerada el sedante herbal más estudiado.',
  'Relajantes',
  'Sedante, hipnótico, ansiolítico, antiespasmódico, relajante muscular',
  ARRAY['insomnio', 'ansiedad', 'sedante', 'sueño profundo'],
  ARRAY['insomnio', 'ansiedad', 'nerviosismo', 'estrés', 'tensión muscular'],
  'Tomar 400-900mg de extracto estandarizado 30-60 minutos antes de acostarse. Para ansiedad: 300-600mg divididos en 2-3 tomas diarias. El efecto completo puede requerir 2-4 semanas de uso regular. No exceder 3 meses de uso continuo sin supervisión.',
  'Causa somnolencia significativa, NO conducir ni operar maquinaria después de tomar. Evitar alcohol. No usar en embarazo/lactancia. Suspender 2 semanas antes de cirugías. Puede empeorar depresión. No combinar con sedantes sin supervisión médica.',
  'Insomnio crónico (especialmente de conciliación). Trastorno de ansiedad generalizada. Agitación nerviosa. Tensión muscular asociada a estrés. Puede ser útil en síndrome de piernas inquietas.',
  'Embarazo y lactancia. Niños menores de 12 años. Hepatopatía. Cirugía programada (suspender 2 semanas antes). Depresión mayor. Uso concomitante con sedantes potentes sin supervisión.',
  'Somnolencia diurna, mareo, dolor de cabeza. Molestias gastrointestinales. Raramente: hepatotoxicidad con uso prolongado (>2 meses). Raramente: excitación paradójica.',
  'Potencia significativamente efectos de sedantes, benzodiacepinas, barbitúricos y alcohol. Interacción con antidepresivos (especialmente IMAOs). Puede potenciar anestésicos. No combinar con antihistamínicos sedantes.',
  'Extracto seco (0.8% ácido valerénico): 400-900mg antes de dormir. Para ansiedad: 300-600mg/día en 2-3 tomas. Tintura (1:5): 3-5ml 1-3 veces al día. Infusión: 2-3g de raíz 1-3 veces al día.',
  'No recomendado en menores de 12 años por falta de estudios de seguridad. En adolescentes >12 años: iniciar con dosis bajas (200-300mg) bajo supervisión médica.',
  ARRAY['oral'],
  'Infusión: 2-3g de raíz seca triturada en 200ml de agua hirviendo, reposar 10-15 minutos tapado. Decocción: hervir raíz 10 minutos (libera más principios activos pero sabor fuerte). Maceración fría: 12 horas en agua fría (reduce mal sabor).',
  false,
  false,
  false,
  'Alto',
  'Bent S, Padula A, Moore D, et al. Valerian for sleep: a systematic review and meta-analysis. Am J Med. 2006;119(12):1005-1012. | Fernández-San-Martín MI, et al. Effectiveness of Valerian on insomnia: a meta-analysis of randomized placebo-controlled trials. Sleep Med. 2010;11(6):505-511.',
  'Advertir sobre NO conducir después de tomar. Monitorear signos de hepatotoxicidad si uso >2 meses (fatiga, ictericia). Evaluar interacciones con otros sedantes. Puede tardar 2-4 semanas en mostrar efecto completo.',
  ARRAY['calidad del sueño', 'latencia de sueño', 'función hepática', 'somnolencia diurna', 'síntomas de depresión'],
  'https://pubmed.ncbi.nlm.nih.gov/17145239/'
);

-- ====================================================================
-- 5. MENTA (Mentha piperita)
-- ====================================================================
INSERT INTO plants (
  name,
  scientific_name,
  description,
  category,
  properties,
  tags,
  ailments,
  usage_instructions,
  warnings,
  therapeutic_indications,
  contraindications,
  side_effects,
  drug_interactions,
  dosage_adults,
  dosage_children,
  administration_route,
  preparation_method,
  safe_pregnancy,
  safe_lactation,
  safe_children,
  evidence_level,
  clinical_studies,
  nursing_notes,
  monitoring_parameters,
  scientific_article_url
) VALUES (
  'Menta',
  'Mentha piperita',
  'Planta aromática con potentes propiedades digestivas y antiespasmódicas. El mentol, su principal componente, relaja el músculo liso intestinal y tiene efecto carminativo, reduciendo gases y cólicos.',
  'Digestivas',
  'Antiespasmódico, carminativo, digestivo, analgésico, antiséptico',
  ARRAY['digestión', 'gases', 'colon irritable', 'refrescante'],
  ARRAY['síndrome de colon irritable', 'dispepsia', 'gases', 'náuseas', 'dolor de cabeza'],
  'Para síndrome de intestino irritable: cápsulas con recubrimiento entérico de 0.2-0.4ml de aceite 3 veces al día entre comidas. Infusión: tomar después de comidas. Aplicación tópica en sienes para cefalea tensional.',
  'NO usar aceite esencial puro en bebés y niños pequeños (puede causar laringoespasmo). Evitar en reflujo gastroesofágico severo (puede empeorar síntomas). Las cápsulas deben ser con recubrimiento entérico. Puede reducir absorción de hierro.',
  'Síndrome de intestino irritable. Dispepsia funcional. Flatulencia y distensión abdominal. Náuseas. Cefalea tensional (aplicación tópica). Congestión nasal leve (inhalación).',
  'Reflujo gastroesofágico severo. Cálculos biliares. Hernia hiatal. Niños menores de 3 años (aceite esencial). Alergia a mentol. Acalasia esofágica.',
  'Acidez, ardor estomacal en personas susceptibles. Reacciones alérgicas (rash, dermatitis de contacto). Raramente: cefalea, temblor. Puede causar irritación anal en dosis altas.',
  'Puede reducir absorción de hierro. Inhibe CYP3A4 (posible interacción con medicamentos metabolizados por esta vía). Puede aumentar niveles de ciclosporina. Evitar con antiácidos (pueden disolver recubrimiento entérico prematuro).',
  'Cápsulas entéricas: 0.2-0.4ml de aceite 3 veces al día (30-60 minutos antes de comidas). Infusión: 1 cucharada de hojas en 200ml agua, 3-4 veces al día. Tintura (1:5): 2-5ml 3 veces al día.',
  'Mayores de 8 años: infusión suave (50-100ml) después de comidas. No usar aceite esencial puro. Cápsulas entéricas solo en adolescentes bajo supervisión médica. Evitar en menores de 3 años.',
  ARRAY['oral', 'topica', 'inhalacion'],
  'Infusión: 1 cucharada de hojas frescas o secas en 200ml de agua a 85-90°C, reposar 5-7 minutos tapado (tapar para conservar aceites volátiles). Aplicación tópica: aceite esencial diluido 2-5% en aceite portador. Inhalación: 2-3 gotas en agua caliente.',
  true,
  false,
  true,
  'Alto',
  'Khanna R, MacDonald JK, Levesque BG. Peppermint oil for the treatment of irritable bowel syndrome: a systematic review and meta-analysis. J Clin Gastroenterol. 2014;48(6):505-512. | Ford AC, et al. Effect of fibre, antispasmodics, and peppermint oil in the treatment of irritable bowel syndrome. BMJ. 2008;337:a2313.',
  'Recomendar cápsulas entéricas para síndrome intestino irritable (liberación en colon). Advertir sobre no usar aceite puro en niños. Monitorear síntomas de reflujo. Tomar entre comidas, no con antiácidos.',
  ARRAY['síntomas gastrointestinales', 'frecuencia de evacuaciones', 'dolor abdominal', 'signos de reflujo'],
  'https://pubmed.ncbi.nlm.nih.gov/24100754/'
);

-- ====================================================================
-- 6. EQUINÁCEA (Echinacea purpurea)
-- ====================================================================
INSERT INTO plants (
  name,
  scientific_name,
  description,
  category,
  properties,
  tags,
  ailments,
  usage_instructions,
  warnings,
  therapeutic_indications,
  contraindications,
  side_effects,
  drug_interactions,
  dosage_adults,
  dosage_children,
  administration_route,
  preparation_method,
  safe_pregnancy,
  safe_lactation,
  safe_children,
  evidence_level,
  clinical_studies,
  nursing_notes,
  monitoring_parameters,
  scientific_article_url
) VALUES (
  'Equinácea',
  'Echinacea purpurea',
  'Planta inmunomoduladora ampliamente estudiada. Contiene alquilamidas, polisacáridos y derivados del ácido cafeico que estimulan la actividad de macrófagos y células NK, fortaleciendo las defensas del organismo.',
  'Inmunológicas',
  'Inmunoestimulante, antiinflamatoria, antiviral, antioxidante',
  ARRAY['sistema inmune', 'resfriados', 'prevención', 'infecciones'],
  ARRAY['resfriado común', 'gripe', 'infecciones respiratorias', 'prevención'],
  'Para prevención: tomar durante temporada de resfriados en ciclos de 8 semanas con 1-2 semanas de descanso. Para tratamiento de resfriado: iniciar al primer síntoma, continuar 7-10 días. No usar más de 8 semanas consecutivas.',
  'No usar en enfermedades autoinmunes (puede estimular sistema inmune). Evitar en inmunosupresión por trasplantes. Suspender si aparecen signos de reacción alérgica. No usar más de 8 semanas continuas. Puede contener alcohol en tinturas.',
  'Prevención y tratamiento de resfriado común (reduce duración y severidad). Infecciones del tracto respiratorio superior. Puede reducir frecuencia de infecciones recurrentes. Soporte inmunológico en personas propensas a resfriados.',
  'Enfermedades autoinmunes (lupus, esclerosis múltiple, artritis reumatoide). Inmunosupresión por trasplantes o VIH. Tuberculosis. Leucemia. Alergia a familia Asteraceae. Uso prolongado >8 semanas sin supervisión.',
  'Reacciones alérgicas (rash, asma, anafilaxia en casos raros). Molestias gastrointestinales leves. Sabor desagradable, entumecimiento temporal de lengua. Raramente: mareo, cefalea.',
  'Puede interferir con inmunosupresores (ciclosporina, corticosteroides). Posible interacción con medicamentos metabolizados por CYP3A4. Puede reducir efectividad de quimioterapia. Evitar con anticoagulantes.',
  'Extracto seco: 300-500mg 3 veces al día. Tintura (1:5): 1-2ml 3 veces al día. Jugo fresco: 6-9ml diarios divididos en 3 tomas. Máximo 8 semanas continuas, descansar 1-2 semanas.',
  'Mayores de 2 años: 1⁄4 de dosis adulto. Mayores de 6 años: 1⁄2 dosis adulto. Uso máximo 10 días. No usar en niños con antecedentes de atopia o alergias múltiples.',
  ARRAY['oral'],
  'Infusión: 1-2g de raíz o parte aérea en 200ml agua hirviendo, reposar 10 minutos. Decocción de raíz: hervir 1-2g 10 minutos (más efectiva). Tintura: macerar raíz fresca en alcohol 40-60° (1:5) durante 14 días.',
  false,
  false,
  true,
  'Moderado',
  'Karsch-Völk M, et al. Echinacea for preventing and treating the common cold. Cochrane Database Syst Rev. 2014;(2):CD000530. | Shah SA, et al. Evaluation of echinacea for the prevention and treatment of the common cold: a meta-analysis. Lancet Infect Dis. 2007;7(7):473-480.',
  'Indicar iniciar al primer síntoma de resfriado. Advertir sobre no usar >8 semanas continuas. Preguntar sobre enfermedades autoinmunes. Evaluar alergias previas a Asteraceae. Puede causar entumecimiento lingual (normal).',
  ARRAY['duración del resfriado', 'severidad de síntomas', 'frecuencia de infecciones', 'signos de alergia'],
  'https://pubmed.ncbi.nlm.nih.gov/24554461/'
);

-- Verificar inserción
SELECT name, scientific_name, evidence_level, safe_pregnancy, safe_lactation, safe_children 
FROM plants 
ORDER BY name;
